const SET_VISIBILITY = 'SET_VISIBILITY';
const SET_TYPE = 'SET_TYPE';
const SET_IS_CORRECT = 'SET_IS_CORRECT';
const SET_MESSAGE = 'SET_MESSAGE';
const SET_FEEDBACK = 'SET_FEEDBACK';


export {
  SET_VISIBILITY,
  SET_TYPE,
  SET_IS_CORRECT,
  SET_MESSAGE,
  SET_FEEDBACK,
};
