const LOAD_GAME = 'LOAD_GAME';
const GAME_IS_LOADING = 'GAME_IS_LOADING';
const SET_GAME_DATA = 'SET_GAME_DATA';
const SET_CURRENT_LEVEL = 'SET_CURRENT_LEVEL';
const NEXT_LEVEL = 'NEXT_LEVEL';
const SET_DONE_LEVEL = 'NEXT_LEVEL';
const SET_CURRENT_AVATAR = 'SET_CURRENT_AVATAR';
const SET_SHOW_QUESTION = 'SET_SHOW_QUESTION';
const SET_SHOW_END_GAME = 'SET_SHOW_END_GAME';

export {
  LOAD_GAME,
  GAME_IS_LOADING,
  SET_GAME_DATA,
  SET_CURRENT_LEVEL,
  NEXT_LEVEL,
  SET_DONE_LEVEL,
  SET_CURRENT_AVATAR,
  SET_SHOW_QUESTION,
  SET_SHOW_END_GAME,
}