const SET_HELPERS = 'SET_HELPERS';
const SHOW_HELPERS = 'SHOW_HELPERS';

// HINTS
const INCREMENT_HINTS = 'INCREMENT_HINTS';
const DECREMENT_HINTS = 'DECREMENT_HINTS';
const SET_HINTS = 'SET_HINTS';

// SKIPS
const INCREMENT_SKIPS = 'INCREMENT_SKIPS';
const DECREMENT_SKIPS = 'DECREMENT_SKIPS';

export {
  SET_HELPERS,
  SHOW_HELPERS,
  INCREMENT_HINTS,
  DECREMENT_HINTS,
  SET_HINTS,
  INCREMENT_SKIPS,
  DECREMENT_SKIPS,
};
