// GLOBAL
const INCREMENT_GLOBAL_TIMER = 'INCREMENT_GLOBAL_TIMER';
const DECREMENT_GLOBAL_TIMER = 'DECREMENT_GLOBAL_TIMER';
const SET_GLOBAL_TIMER_PERIOD = 'SET_GLOBAL_TIMER_PERIOD';
const SET_GLOBAL_TIME_SPENT = 'SET_GLOBAL_TIME_SPENT';
const RESET_GLOBAL_TIME_SPENT = 'RESET_GLOBAL_TIME_SPENT';

// LEVEL
const INCREMENT_TIMER = 'INCREMENT_TIMER';
const DECREMENT_TIMER = 'DECREMENT_TIMER';
const SET_TIMER_PERIOD = 'SET_TIMER_PERIOD';
const SET_TIME_SPENT = 'SET_TIME_SPENT';
const RESET_TIME_SPENT = 'RESET_TIME_SPENT';

export {
  INCREMENT_GLOBAL_TIMER,
  DECREMENT_GLOBAL_TIMER,
  SET_GLOBAL_TIMER_PERIOD,
  SET_GLOBAL_TIME_SPENT,
  RESET_GLOBAL_TIME_SPENT,
  INCREMENT_TIMER,
  DECREMENT_TIMER,
  SET_TIMER_PERIOD,
  SET_TIME_SPENT,
  RESET_TIME_SPENT,
};
