const PLAY_SOUND = 'PLAY_SOUND';
const STOP_SOUND = 'STOP_SOUND';
const MUTE_SOUND = 'MUTE_SOUND';
const TOGGLE_MUTE_SOUND = 'TOGGLE_MUTE_SOUND';
const SET_SOUNDS = 'SET_SOUNDS';

export {
  PLAY_SOUND,
  STOP_SOUND,
  MUTE_SOUND,
  TOGGLE_MUTE_SOUND,
  SET_SOUNDS,
};
